version: '3'
services:
  webserver:
    image: nginx
    container_name: 'nginx'
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
      args:
        NODE_ENV: production  # Example build argument for the frontend service
    ports:
      - '8081:80'
    environment:
      NODE_ENV: PRODUCTION

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - '8089:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  apilayer:
    build:
      context: ./apilayer
      dockerfile: Dockerfile
      args:
        TOKEN_VALIDITY_TIME: ${TOKEN_VALIDITY_TIME}
        CLIENT_USER: ${CLIENT_USER}
        CLIENT_PASSWORD: ${CLIENT_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_HOST}
        DATABASE_DOCKER_CONTAINER_IP_ADDRESS: backend
    ports:
      - '8087:8087'
    environment:
      TOKEN_VALIDITY_TIME: ${TOKEN_VALIDITY_TIME} # in minutes
      CLIENT_USER: ${CLIENT_USER}
      CLIENT_PASSWORD: ${CLIENT_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DATABASE_DOCKER_CONTAINER_IP_ADDRESS: backend
    volumes:
      - api_layer:/usr/src/
    depends_on:
      - backend

volumes:
  pg_data:
  api_layer:
  migrations:
