version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8089:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
