version: '3'
services:
  webserver:
    image: nginx
    container_name: 'nginx'
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
      args:
        NODE_ENV: production  # Example build argument for the frontend service
    ports:
      - '8081:80'
    environment:
      NODE_ENV: PRODUCTION

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9001"

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - '8089:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  apilayer:
    build:
      context: .
      dockerfile: ./apilayer/Dockerfile
      args:
        TOKEN_VALIDITY_TIME: ${TOKEN_VALIDITY_TIME}
        CLIENT_USER: ${CLIENT_USER}
        CLIENT_PASSWORD: ${CLIENT_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_HOST}
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        MINIO_APP_BUCKET_NAME: ${MINIO_APP_BUCKET_NAME}
        MINIO_APP_BUCKET_LOCATION: ${MINIO_APP_BUCKET_LOCATION}
        MINIO_APP_LOCALHOST_URL: ${MINIO_APP_LOCALHOST_URL}
        DATABASE_DOCKER_CONTAINER_IP_ADDRESS: backend
    ports:
      - '8087:8087'
    environment:
      ENVIRONMENT: PRODUCTION
      TOKEN_VALIDITY_TIME: ${TOKEN_VALIDITY_TIME} # in minutes
      CLIENT_USER: ${CLIENT_USER}
      CLIENT_PASSWORD: ${CLIENT_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_APP_BUCKET_NAME: ${MINIO_APP_BUCKET_NAME}
      MINIO_APP_BUCKET_LOCATION: ${MINIO_APP_BUCKET_LOCATION}
      MINIO_APP_LOCALHOST_URL: ${MINIO_APP_LOCALHOST_URL}
      DATABASE_DOCKER_CONTAINER_IP_ADDRESS: backend
    volumes:
      - api_layer:/usr/src/
    depends_on:
      - backend

volumes:
  pg_data:
  minio_data:
  minio_config:
  api_layer:
  migrations:
