#!/bin/sh

# File: _loadProdEnvVariables.sh
# Description: Loads the required environment variables in production environment.

sleep 2
echo "loading environment variables"

# feature flags for application level services
_SENDGRID_EMAIL_SERVICE="false"


# geocoding details
GEOCODING_MAP_API_KEY=""

# sendgrid details
SEND_GRID_API_KEY=""
SEND_GRID_USER="Earmuffjam@FleetWise-Admin"
SEND_GRID_USER_EMAIL_ADDRESS="earmuffjam@gmail.com"

# ether otp generator
_OTP_GENERATOR_SERVICE="false"
OTP_GENERATOR_API_KEY="c4ad14d1-207b-4833-a55f-b9087b9d71f6"

# postgres db parameters
POSTGRES_DB="community"
POSTGRES_USER="postgres"
POSTGRES_PASSWORD="home"
POSTGRES_HOST=5432

# minio user
MINIO_ROOT_USER="community_public"
MINIO_ROOT_PASSWORD="password"
MINIO_APP_LOCALHOST_URL=minio:9000
MINIO_APP_BUCKET_NAME="images"
MINIO_APP_BUCKET_LOCATION="us-east-1"

# general users
CLIENT_USER="community_public"
CLIENT_PASSWORD="password"

# jwt token details
TOKEN_SECRET_KEY="cd2f45b5-b87e-42ea-8725-85131129bcc8"
TOKEN_VALIDITY_TIME=3600

# test users
COMMUNITY_TEST_USER="community_test"

# UI env variables
REACT_APP_ENVIRONMENT="PROD"
REACT_APP_LOCALHOST_URL=http://localhost:8087
REACT_APP_LOCALHOST_URL_SOCKET_BASE_URL=ws://localhost:8087
DATABASE_DOCKER_CONTAINER_IP_ADDRESS=localhost
DATABASE_DOCKER_CONTAINER_NAME="mashed-backend-1"
DATABASE_DOCKER_CONTAINER_PORT=8089

# Create .env file and set parameters
cat <<EOF > .env
POSTGRES_DB=$POSTGRES_DB
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_HOST=$POSTGRES_HOST

CLIENT_USER=$CLIENT_USER
CLIENT_PASSWORD=$CLIENT_PASSWORD
COMMUNITY_TEST_USER=$COMMUNITY_TEST_USER

MINIO_ROOT_USER=$MINIO_ROOT_USER
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
MINIO_APP_BUCKET_NAME=$MINIO_APP_BUCKET_NAME
MINIO_APP_BUCKET_LOCATION=$MINIO_APP_BUCKET_LOCATION
MINIO_APP_LOCALHOST_URL=$MINIO_APP_LOCALHOST_URL

DATABASE_DOCKER_CONTAINER_NAME=$DATABASE_DOCKER_CONTAINER_NAME
DATABASE_DOCKER_CONTAINER_PORT=$DATABASE_DOCKER_CONTAINER_PORT
DATABASE_DOCKER_CONTAINER_IP_ADDRESS=$DATABASE_DOCKER_CONTAINER_IP_ADDRESS

TOKEN_SECRET_KEY=$TOKEN_SECRET_KEY
TOKEN_VALIDITY_TIME=$TOKEN_VALIDITY_TIME

GEOCODING_MAP_API_KEY=$GEOCODING_MAP_API_KEY

_SENDGRID_EMAIL_SERVICE=$_SENDGRID_EMAIL_SERVICE
SEND_GRID_API_KEY=$SEND_GRID_API_KEY
SEND_GRID_USER=$SEND_GRID_USER
SEND_GRID_USER_EMAIL_ADDRESS=$SEND_GRID_USER_EMAIL_ADDRESS

_OTP_GENERATOR_SERVICE=$_OTP_GENERATOR_SERVICE
OTP_GENERATOR_API_KEY=$OTP_GENERATOR_API_KEY

REACT_APP_LOCALHOST_URL=$REACT_APP_LOCALHOST_URL
REACT_APP_LOCALHOST_URL_SOCKET_BASE_URL=$REACT_APP_LOCALHOST_URL_SOCKET_BASE_URL
EOF
echo "finished compiling required variables."