#!/bin/sh

# File: _loadEnvVariables.sh
# Description: Loads the required environment variables

sleep 2
echo "loading environment variables"

DEBUG="DEBUG"

# feature flags for application level services
_SENDGRID_EMAIL_SERVICE="false"

# geocoding details
GEOCODING_MAP_API_KEY="65935a9a69a55044609123vne64b72b"

# sendgrid details
SEND_GRID_API_KEY=""
SEND_GRID_USER="Earmuffjam@FleetWise-Admin"
SEND_GRID_USER_EMAIL_ADDRESS="earmuffjam@gmail.com"

# ether otp generator
_OTP_GENERATOR_SERVICE="false"
OTP_GENERATOR_API_KEY="7f8fd9ee-df97-47cf-b07b-91b4d2327a1c"

# postgres db parameters
POSTGRES_DB="community"
POSTGRES_USER="postgres"
POSTGRES_PASSWORD="home"
POSTGRES_HOST=5432

# minio user
MINIO_ROOT_USER="community_public"
MINIO_ROOT_PASSWORD="password"
MINIO_APP_LOCALHOST_URL=localhost:9000
MINIO_APP_BUCKET_NAME="images"
MINIO_APP_BUCKET_LOCATION="us-east-1"

# general users
CLIENT_USER="community_public"
CLIENT_PASSWORD="password"

# jwt token details
TOKEN_SECRET_KEY="41f50173-4383-45ae-acb8-393dc27af446"
TOKEN_VALIDITY_TIME=3600

# test users
COMMUNITY_TEST_USER="community_test"

# UI localhost uri
REACT_APP_LOCALHOST_URL=http://localhost:8087
REACT_APP_LOCALHOST_URL_SOCKET_BASE_URL=ws://localhost:8087
DATABASE_DOCKER_CONTAINER_NAME="mashed-backend-1"
DATABASE_DOCKER_CONTAINER_IP_ADDRESS="localhost"
DATABASE_DOCKER_CONTAINER_PORT=8089

# Create .env file and set parameters
cat <<EOF > .env
POSTGRES_DB=$POSTGRES_DB
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_HOST=$POSTGRES_HOST

CLIENT_USER=$CLIENT_USER
CLIENT_PASSWORD=$CLIENT_PASSWORD
COMMUNITY_TEST_USER=$COMMUNITY_TEST_USER

MINIO_ROOT_USER=$MINIO_ROOT_USER
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
MINIO_APP_BUCKET_NAME=$MINIO_APP_BUCKET_NAME
MINIO_APP_BUCKET_LOCATION=$MINIO_APP_BUCKET_LOCATION
MINIO_APP_LOCALHOST_URL=$MINIO_APP_LOCALHOST_URL

DATABASE_DOCKER_CONTAINER_NAME=$DATABASE_DOCKER_CONTAINER_NAME
DATABASE_DOCKER_CONTAINER_PORT=$DATABASE_DOCKER_CONTAINER_PORT
DATABASE_DOCKER_CONTAINER_IP_ADDRESS=$DATABASE_DOCKER_CONTAINER_IP_ADDRESS

TOKEN_SECRET_KEY=$TOKEN_SECRET_KEY
TOKEN_VALIDITY_TIME=$TOKEN_VALIDITY_TIME

GEOCODING_MAP_API_KEY=$GEOCODING_MAP_API_KEY

_SENDGRID_EMAIL_SERVICE=$_SENDGRID_EMAIL_SERVICE
SEND_GRID_API_KEY=$SEND_GRID_API_KEY
SEND_GRID_USER=$SEND_GRID_USER
SEND_GRID_USER_EMAIL_ADDRESS=$SEND_GRID_USER_EMAIL_ADDRESS

_OTP_GENERATOR_SERVICE=$_OTP_GENERATOR_SERVICE
OTP_GENERATOR_API_KEY=$OTP_GENERATOR_API_KEY

REACT_APP_LOCALHOST_URL=$REACT_APP_LOCALHOST_URL
REACT_APP_LOCALHOST_URL_SOCKET_BASE_URL=$REACT_APP_LOCALHOST_URL_SOCKET_BASE_URL

DEBUG=$DEBUG
EOF
echo "finished compiling required variables."